export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary': '#4d2600',
        'on-tertiary-fixed': '#201b0f',
        'tertiary': '#cfc5b2',
        'primary': '#ffb77d',
        'surface-dim': '#131313',
        'on-secondary-fixed': '#002020',
        'secondary-fixed-dim': '#2ddbde',
        'outline-variant': '#564334',
        'tertiary-fixed-dim': '#cfc5b2',
        'primary-fixed-dim': '#ffb77d',
        'surface-container-high': '#2a2a2a',
        'on-surface-variant': '#ddc1ae',
        'surface-tint': '#ffb77d',
        'inverse-primary': '#904d00',
        'on-secondary': '#003738',
        'error-container': '#93000a',
        'surface-container': '#20201f',
        'primary-fixed': '#ffdcc3',
        'outline': '#a48c7a',
        'on-secondary-fixed-variant': '#004f51',
        'tertiary-container': '#b2a997',
        'on-primary-container': '#623200',
        'surface-variant': '#353535',
        'primary-container': '#ff8c00',
        'surface-bright': '#393939',
        'on-background': '#e5e2e1',
        'surface': '#131313',
        'inverse-on-surface': '#313030',
        'tertiary-fixed': '#ece1ce',
        'on-error-container': '#ffdad6',
        'on-error': '#690005',
        'on-secondary-container': '#005253',
        'background': '#131313',
        'error': '#ffb4ab',
        'secondary-fixed': '#5af8fb',
        'on-tertiary': '#353022',
        'on-surface': '#e5e2e1',
        'surface-container-highest': '#353535',
        'secondary-container': '#00cdd0',
        'secondary': '#46eaed',
        'surface-container-low': '#1c1b1b',
        'on-tertiary-container': '#443e30',
        'on-primary-fixed': '#2f1500',
        'on-tertiary-fixed-variant': '#4d4638',
        'surface-container-lowest': '#0e0e0e',
        'on-primary-fixed-variant': '#6e3900',
        'inverse-surface': '#e5e2e1',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'md': '24px',
        'xs': '4px',
        'lg': '40px',
        'base': '8px',
        'margin-desktop': '48px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'sm': '12px',
        'xl': '64px',
      },
      fontFamily: {
        'display-lg': ['"EB Garamond"', 'serif'],
        'label-lg': ['"Work Sans"', 'sans-serif'],
        'title-lg': ['"EB Garamond"', 'serif'],
        'body-md': ['"Work Sans"', 'sans-serif'],
        'body-lg': ['"Work Sans"', 'sans-serif'],
        'label-sm': ['"Work Sans"', 'sans-serif'],
        'headline-md': ['"EB Garamond"', 'serif'],
        'headline-lg-mobile': ['"EB Garamond"', 'serif'],
        'headline-lg': ['"EB Garamond"', 'serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
      },
      animation: {
        'flicker': 'flicker 2s infinite ease-in-out',
        'molten-glow': 'molten-glow 3s ease-in-out infinite',
        'fire-flicker': 'fire-flicker 4s infinite',
        'ember-float': 'ember-float linear infinite',
        'spark-burst': 'spark-burst 0.8s cubic-bezier(0, .9, .57, 1) forwards',
      },
      keyframes: {
        'flicker': {
          '0%, 100%': { opacity: '0.6', filter: 'drop-shadow(0 0 8px #ffb77d)' },
          '50%': { opacity: '1', filter: 'drop-shadow(0 0 15px #ff8c00)' },
        },
        'molten-glow': {
          '0%, 100%': { boxShadow: '0 0 20px #ff8c00, inset 0 0 10px rgba(255, 183, 125, 0.5)', textShadow: '0 0 8px rgba(255, 255, 255, 0.8)' },
          '50%': { boxShadow: '0 0 35px #93000a, inset 0 0 20px rgba(255, 82, 0, 0.8)', textShadow: '0 0 12px rgba(255, 255, 255, 1)' },
        },
        'fire-flicker': {
          '0%': { opacity: '0.4', transform: 'scale(1) translateY(0)' },
          '25%': { opacity: '0.8', transform: 'scale(1.1) translateY(-2px)' },
          '50%': { opacity: '0.5', transform: 'scale(0.95) translateY(0)' },
          '75%': { opacity: '0.9', transform: 'scale(1.05) translateY(-1px)' },
          '100%': { opacity: '0.4', transform: 'scale(1) translateY(0)' },
        },
        'ember-float': {
          '0%': { transform: 'translateY(0) rotate(0deg)', opacity: '0' },
          '20%': { opacity: '0.8' },
          '100%': { transform: 'translateY(-100vh) rotate(360deg)', opacity: '0' },
        },
        'spark-burst': {
          '0%': { transform: 'translate(0, 0) scale(1)', opacity: '1' },
          '100%': { transform: `translate(var(--spark-x), var(--spark-y)) scale(0)`, opacity: '0' },
        },
      },
    },
  },
  plugins: [],
}